import type { Metadata } from "next"
import { redirect } from "next/navigation"
import { auth } from "@/auth"
import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function NoAuthLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  if (session) redirect("/dashboard")

  return <main className="container mx-auto">{children}</main>
}
